bergercookie/asm-lsp

Cargo.toml
src/bin/main.rs
src/lib.rs
src/lsp.rs
src/types.rs
src/x86_parser.rs

And the crate upstream have changed a lot , do you have time to make changes?

fix: fix openssl problem and cargo clippy

---

Cargo.lock
Cargo.toml
src/x86_parser.rs

Initial code to implement caching as described in #13  .
This code currently just has a placeholder for grabbing the CLI refresh cache argument (Lines 226-227 in the diff of src/x86_parser.rs below) which can be swapped out with the way the project typically handles CLI args.
(Reopened a new PR as I messed up the last one)
Closes #13

Add caching

---

.github/workflows/lint_and_test.yml
Cargo.lock
Cargo.toml
src/x86_parser.rs

Here's a first pass on adding a unit test for ``populate_instructions``. 
Not certain about some details but thought this would be a good place to start.
Closes #12

Add unit-testing

---

src/bin/main.rs
src/lsp.rs

this gives an outline to the document, and also enables search by symbol
in some editors (at least lunarvim). Currently only labels are indexed,
giving a flat structure to an assembly file (and easy jump to a given
label).

handle DocumentSymbolRequest

---

src/lsp.rs

I'm running into some issues implementing a tree-sitter query to implement #47, but in the process I figured out some stuff that allowed me to significantly clean up and improve the tree-sitter queries in `get_comp_resp()`. The entire function now only uses one tree-sitter query. Furthermore, said query now matches registers when they're used in "`ptr`" or "`ERRROR`" tree-sitter nodes, allowing additional autocomplete suggestions in lines that didn't work previously. A few example screenshots from `samples/gas.s` are given below

Autocomplete improvements

---

src/bin/main.rs

This PR improves hover support. Currently when the server receives a hover request, it calls `get_word_from_file_params()`. This can lead to issues if the document has been modified but not saved yet. For example:
This issue is fixed by using the server's in-memory copy of the buffer, which gets updates every time a change is made:
While it's not the goal of this PR, eliminating the file I/O should give a small performance boost as well. :)

Remove file read from hover code

---

README.md
src/lsp.rs

resolves #78
I tried searching around a bit and am curious where exactly this requirement comes from. Could you point me in the general area to look? I wouldn't mind poking around a bit.

docs: `.git` in root dir requirement

---

asm-lsp_config_schema.json

Missed this in my initial PR for z80 (#59).

chore: update asm-lsp_config_schema.json

---

src/bin/main.rs

For some reason, the call to `join` for the `writer` thread of the server's `connection` hangs more often than not. I'm not entirely sure why this is happening, but we can just skip joining the worker threads at server shutdown for now.
cc @ChillerDragon
Closes #106

fix: Server process fails to join writer thread causing process to hang

---

Cargo.lock

Planning on putting this through after merging #118

chore: Bump dependencies

---

src/lsp.rs

This adds some useful logs around the server loading its per-project config file. Added as part of investigating #127

fix: Add logs to config related code

---

src/lsp.rs

Allows the server to detect `compile_commands.json`/ `compile_flags.txt` in the project's root directory in addition to the root build directory.

feat: detect compilation database from project's root

---

src/handle.rs

Missed this in my initial implementation!

fix: respect default_diagnostics config option

---

src/lsp.rs

Still haven't had time to dig into the root cause of this, but in the meantime this PR places a bounds check before *all* calls to tree-sitter's `.utf8_text()` method. This should eliminate the related crashes.
Closes #154

fix: Add range checks before all calls to tree-sitter's `utf8_text()`

---

.github/workflows/lint_and_test.yml

chore(CI): update rust version to 1.82

---

.github/workflows/lint_and_test.yml

Death, taxes, and CI breaking randomly...

fix(CI): use Ruby 3.2.6 on Ubuntu runners

---

asm-lsp/bin/main.rs

feat: add version subcommand

---

asm-lsp/lsp.rs
asm-lsp/types.rs

There are two problems at play here:
1. If you open a buffer that doesn't have a corresponding file written to disk (i.e., `nvim some_new_asm_file.s`), the server will crash. This is because we attempt to canonicalize the path associated with a request. This canonicalization can fail if the path is malformed, or if it just points to a file that doesn't exist. I've refactored `get_config` to handle this case. If a path cannot be canonicalized, it is still returned and a warning is issued to the log.
2. First reported in [this post](https://www.reddit.com/r/emacs/comments/1gv7wss/problem_with_asmlsp_in_emacs/) on r/emacs. I wasn't aware of this until now, but the lsp spec is actually incredibly vague regarding what constitutes a valid URI. From [the …

fix: uri encodings

---

README.md

chore: update docs to indicate `gen-config` subcommand is only available on master branch

---

.github/workflows/lint_and_test.yml

fix(CI): force symbolic link for ruby dependency

---

README.md

fix(docs): add avr as possible arch value in README

---

.github/workflows/publish.yml
Cargo.lock
Cargo.toml
asm_docs_parsing/Cargo.toml

- Bumps dependencies
- Bumps the project's version to 0.10.0

bump dependencies, prepare for 0.10.0 release

---

README.md

I've taken a break from the project to focus on lspresso-shot. While the development of my new testing library will continue, I'd like to spend a little more time here as well. Looking to tackle FASM in the next week or so.

fix(docs): minor README updates

---

asm-lsp/parser.rs
editors/code/src/extension.ts

Problem when you install extension for vscode is typing very lagging, because showup a lot of result

Reduce lag when typing with VSCode extension

---

README.md
asm-lsp/parser.rs
asm-lsp/test.rs
asm_docs_parsing/src/main.rs

fix: update docs and tests for `mips` and `mars`

---

asm-lsp/lsp.rs

Errors outputted by fasm are in a format that can't be correctly parsed by our current diagnostic code. For example:
```
main.S [12]:
syscall 1, 1, msg, msg_size
processed: syscall 1,1,msg,msg_size
error: extra characters on line.
```
Special case parsing if the fasm assembler is enabled. 
CC @Super-Botman if you'd like a chance to try this out before I merge.
- Closes #251

fix(lsp): parse diagnostics from fasm assembler
