bergercookie/asm-lsp

Cargo.toml
src/x86_parser.rs

old version quick-xml has desprate function, and maybe cannot be compiled by new rust anymore, so upgrade it
```
the following packages contain code that will be rejected by a future version of Rust: quick-xml v0.18.1
```

chore: update quick-xml

---

src/x86_parser.rs

The lsp server was crashing on startup due to the regex not capturing anything, it seemed to be because the site html had changed.

Changed regex to fit changes on 'https://www.felixcloutier.com/x86/'

---

Cargo.lock
src/bin/main.rs
src/types.rs
src/x86_parser.rs

Change the `names_to_instructions` HashMap to accept keys of `(Arch, &str)` so x86_64 instructions no longer overwrite x86 instructions of the same name at load time. When both x86 and x86_64 have an instruction of the same name, both are displayed when using hover functionality,

Fix opcode collisions

---

.gitignore
Cargo.lock
Cargo.toml
README.md
src/bin/main.rs
src/lsp.rs
src/types.rs

Add select target feature, allowing users to specify in a .asm-lsp config file which assembler(s) and architecture(s) they want the LSP to target.
Feature likely needs more investigation regarding workspaceFolders.

First pass on adding select target feature

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/publish.yml
.github/workflows/tests.yml

adds some basic workflows that handle 
- checking documentation
- auditing dependencies
- testing formatting
- build testing
- unit testing (just the groundwork)
- publishing crates
I've tested the workflows best I could using act, the publish workflow could not be tested as it needs tagging.
Closes #11

CI: add workflows

---

Cargo.lock

Updates the out-of-date cargo lock. 
Unblocks `nixpkgs` packaging.

chore: update Cargo lockfile

---

src/x86_parser.rs

I noticed the regex used to parse the online docs was adding an extra /x86/ to the hover window's displayed url, yielding an invalid link. 
Before:
Link yielded: https://www.felixcloutier.com/x86/x86/pop
After:
Link yielded: https://www.felixcloutier.com/x86/pop
I fixed this by adding x86/ explicitly into the regex, moving it out of the capture group used for the `url_suffix` variable initialized at `src/x86_parser.rs` line 242  in the diff. The old regex is left in the file (commented out) for reference.
Closes #19

Fix x86 online docs regex, removing extra /x86/

---

src/bin/main.rs
src/lsp.rs

Fixes the behavior mentioned in #23 where intel syntax instruction names have hover support only if they aren't capitalized. E.g., ``MOV`` would work but ``mov`` would not.

Fix case sensitivity issue with intel syntax instruction names

---

registers/x86.xml
registers/x86_64.xml
samples/gas.s
src/bin/main.rs
src/lib.rs
src/lsp.rs
src/types.rs
src/x86_parser.rs

First pass on adding hover support for CPU registers. Hover info includes  type, width, and a brief description. If the register's bits are used as flags, the meaning of each bit is also displayed.
I wasn't able to find a resource analogous to the opcode xml files that this repo has for the instruction sets, so I created my own (``registers/x86.xml`` and ``registers/x86_64.xml``) using https://wiki.osdev.org/CPU_Registers_x86 , https://wiki.osdev.org/CPU_Registers_x86-64 , and a few wikipedia pages for the SIMD registers.
I did my best to follow the general flow/ style already established for the instruction sets, which made implementing this very straightforward. Filtering out registers from certain architectures via the ``.asm-lsp.toml`` file works just as with the instructions. I'd …

Add register hover support

---

Cargo.lock
Cargo.toml

FYI @WillLillis 
For 0.6.0 I just pushed this version manually from CLI - https://crates.io/crates/asm-lsp/0.6.0
```
CARGO_REGISTRY_TOKEN=... cargo publish
```

Update dependencies and bump to 0.6.0

---

src/lsp.rs

A bit minor/ nitpicky, but the repeated code to check for cursor overlap for each TS query match inside ``get_comp_resp()`` was kinda bothering me. It turns out refactoring that to a simple macro was fairly straightforward. I think this cleans up the logic a decent amount, thoughts?

refactor: Use macro to check cursor overlap with TS query matches

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/lsp.rs

I found a [crate](https://crates.io/crates/lsp-textdocument) that takes care of all the messy translations needed to take advantage of tree-sitter's incremental parsing. Edit information is now communicated incrementally to the server. Edits are applied to the in memory copy of the buffer and the tree-sitter tree eagerly, but the tree re-parsed (incrementally!) in a lazy fashion whenever a completion request is received.
As far as I can tell, this is working at parity with the less-efficient (but simpler) "full-text" syncing method, but I think a second set of eyes testing could help.
Closes #31

Incremental parsing

---

Cargo.lock
Cargo.toml
README.md
src/lsp.rs

This adds the option to have a global config file in ``~/.config/asm-lsp/``. If present, a project's configuration file will override the global config.
Closes #41

feat: Global config

---

Cargo.lock
Cargo.toml
samples/demangling/a.cpp
samples/demangling/a.s
src/bin/main.rs
src/lsp.rs

This PR adds name demangling support on hover using the [symbolic crate](https://crates.io/crates/symbolic). This crate supports demangling for C++ (GCC, clang and MSVC), Objective C / Objective C++, Rust, and Swift. As one of the main goals of this LSP is to help users explore the assembly output of a compiled program, I think this feature should be helpful. Here's an example gif:

feat: demangle on hover

---

asm-lsp_config_schema.json
src/bin/main.rs

This PR adds a JSON schema for the project's `.asm-lsp.toml` config file. I validated the schema using the [pajv](https://github.com/json-schema-everywhere/pajv) CLI tool. I tried but was unable to find any other tools that validated `.toml` data files against json schemas. If anyone else is aware of such a tool, feel free to comment here. 
I'm not super familiar with these tools/ how they're used yet. Since you opened the issue @Freed-Wu,  if you could test the schema (I'm not familiar with which tools actually use this information) I have here to make sure everything is set before merging that would be greatly appreciated. 😄 
If this schema looks ok, I'll go ahead and open a PR on [schemastore's repo](https://github.com/SchemaStore/schemastore) to add it for others to use. 
Closes #60

feat: Add JSON schema

---

Cargo.lock

Fixes a failing security audit via `cargo-deny`. Updates `h2` and `wasm-bindgen` crates.

Address cargo-deny security advisories

---

src/bin/main.rs
src/lsp.rs

This PR adds basic document link on hover as requested in #45.
At start up time, the server issues ``gcc`` and ``clang`` commands to see the default header search paths on the current system. The output from those commands is parsed, and when a hover request is made those directories are searched for a file with a name matching the requested hover word. If there are better ways to grab this information (e.g. better commands, or some gcc/clang bindings to get the information programmatically), I'd be thrilled to swap out what I currently have. This functions well enough for basic system headers, but by no means provides complete coverage.  Here's a gif example:
If this is ok to merge with the current approach, I think it may be a good idea to add an optional "additional_includes" field to …

feat: Header doc link

---

src/x86_parser.rs

While testing something else I realized some of the instruction names inside of xml files are actually in upper case, for example XOR's entry:
```xml
<Instruction name="XOR" summary="Logical Exclusive OR">
<InstructionForm gas-name="xorb" go-name="XORB">
<Operand type="al" input="true" output="true"/>
<Operand type="imm8"/>
<Encoding>
<Opcode byte="34"/>
<Immediate size="1" value="#1"/>
</Encoding>
</InstructionForm>
<InstructionForm gas-name="xorb" go-name="XORB">
...
</Instruction>
```
This means that currently the LSP will respond to a hover request for `XOR`, but not for `xor`. This PR provides a patch by adding both the `.to_uppercase()` and `.to_lowercase()` variants of the instruction name at load time. A cleaner solution would be to just do case insensitive insensitive lookup into …

Fix case sensitivity bug

---

.github/workflows/lint_and_test.yml
src/bin/main.rs

Ran into some issues with the windows github checks while testing out a feature related to #75. Not entirely sure why they broke, but these changes appear to fix things.

Fix windows workflows

---

registers/x86_64.xml
src/bin/main.rs
src/types.rs
src/x86_parser.rs

This PR moves some of the unrelated work out of #57, as it's already too long to begin with :)
This change has the program read the instruction set information at the top of the xml file and assign the result (`x86` or `x86_64`) to each `Instruction` or `Register` struct  as they're being created, rather than with the additional `map()` calls that are currently in `main()`. This won't have any observable impact on performance (Just a 0.013s average speedup for the time to load all 4 xml files, measured over 10 trials each)/ behavior, but should help to clean things up a bit. :)

refactor: Assign Register and Instruction `arch` field at read time

---

directives/gas_directives.xml
src/bin/main.rs
src/lib.rs
src/lsp.rs
src/types.rs
src/x86_parser.rs

This PR (sorry it's a bit long!) adds hover and autocomplete support for Gas directives. Adding this was relatively straightforward code-wise, as the majority of time went into writing the XML file. I initially looked into writing a python script to pull the information together, but there were enough oddities/ things to manually edit in the [docs](https://sourceware.org/binutils/docs-2.41/as/Pseudo-Ops.html) that I just wrote it by hand (The [LuaSnip](https://github.com/L3MON4D3/LuaSnip) plugin was very helpful in this regard).
Huge thanks to @Freed-Wu for making the request and linking the relevant documentation!
Closes #46

feat: Hover and Autocomplete for Gas directives

---

Cargo.lock
Cargo.toml

This is the first time I'm doing this, but going off of [this comment](https://github.com/bergercookie/asm-lsp/pull/29#issuecomment-1826858152), I believe all that's required for a new version to be published is for 
- The package number to be updated in `Cargo,toml`
- A new tag to get pushed up

Update package number in Cargo.toml in prep for 0.7.0 release

---

Cargo.lock
Cargo.toml
src/lib.rs
src/lsp.rs
src/test.rs
src/types.rs
src/x86_parser.rs

This PR does a few things 
* Changes the information maps (`names_to_instructions`, `names_to_registers`, and `names_to_directives`) to hold owned copies of their respective data, rather than references to the data inside of separate `Vec`. This change was made in order to facilitate easier setup for unit tests, as well as in preparation for the refactor to support #75.
* Add a basic unit testing framework. Essential (read-only) parts of the server (just the aforementioned maps for now) are initialized and placed in a static variable accessible to all of the tests. 
* Added unit tests for hover capabilities. The tests added don't offer complete coverage, but do touch a decent chunk of use cases. As bugs are reported (and fixed), the associated reproduction cases can be added as further …

Unit test framework, hover tests, fix hash collision bug

---

src/test.rs
src/types.rs

This PR builds off of #83, adding unit tests for the server's autocomplete functionality. The tests cover the following:
* x86/x86_64 instructions
* x86/x86_64 registers
* gas directives
* z80 instructions
* z80 registers
While there are still some features I'd like to add testing for (e.g. view references, goto definition, etc.), with these additions the majority of the server's functionality is covered. As such, I'll count this as "good enough" for now for the unit testing task in #80.

Add autocomplete testing framework, tests

---

src/lsp.rs
src/test.rs
src/types.rs
src/x86_parser.rs

This reverts some of the changes I made in #83. In particular, it makes it so that the global maps once again hold references to data in underlying vectors, rather than owning the data themselves for each entry. This won't be an issue for the upcoming serialization changes, as we can still use the vectors, and then populate the hashmaps after deserialization. This should improve our memory footprint, especially as we add new architectures. 
In regards to the testing code, this change slows down the tests considerably, as the global stores have to be initialized on every test. On the upside, however, it improves the error output when a test fails (there's a lot less noise since there's no longer a mutex to poison).

fix: Revert switch to owned data in global maps

---

src/bin/main.rs
src/handle.rs
src/lib.rs
src/types.rs

This PR continues the refactor/ cleanup from #87 by pulling most of the logic out of the main loop and into various handler functions (inside the new `src/handle.rs` file). Additionally, this also adds timing logs for each request and notification, as mentioned in #80.

refactor: Extract main loop in handle fns, add timing logs

---

.github/workflows/lint_and_test.yml

This change to the github workflows fixes the issue where workflows won't trigger if a source file isn't modified, e.g. when `README.md` is updated. This has been an issue in a few PRs, most recently in #79. Given that changes to the data files (anything in `registers`, `opcodes`, or `directives` currently) can change behavior in the executable, I think it makes more sense anyway to just run the entire test suite on any change to the repo.

fix: remove path restrictions for ci test runs

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/handle.rs
src/lsp.rs
src/test.rs
src/types.rs

This PR does a few things
* Supports multiple documents at once
- Done in prep for supporting compile_commands.json (see #77, #85)
- This is also just a good idea in and of itself
* Upgrade the [lsp-textdocument](https://github.com/GiveMe-A-Name/lsp-textdocument/tree/main) dependency
- This eliminates a versioning conflict, allowing us to alos upgrade the [lsp-types](https://github.com/gluon-lang/lsp-types) dependency. With the `Hash` trait derived for the `Location` struct in https://github.com/gluon-lang/lsp-types/pull/279, we can now clean up some logic [around here](https://github.com/bergercookie/asm-lsp/blob/97b473e409ded1953f6e6baf1853e48b60e31ab3/src/lsp.rs#L885) in a follow-up PR as well

feat: Support multiple documents, other misc. changes

---

.github/workflows/lint_and_test.yml
.vscode/extensions.json
.vscode/launch.json
.vscode/package-lock.json
.vscode/tasks.json
README.md
editors/code/.eslintignore
editors/code/.eslintrc.js
editors/code/.gitignore
editors/code/.vscodeignore
editors/code/README.md
editors/code/package-lock.json
editors/code/package.json
editors/code/src/extension.ts
editors/code/tsconfig.json

I haven't personally spent much time with VSCode (so I may be missing some fairly obvious gotcha's here), but it's an incredibly popular editor and it would be really nice to enable its users to try out our server. After some tinkering I was able to get a development debug build to work:
I pieced this together by looking over similar implementations in [htmx-lsp](https://github.com/ThePrimeagen/htmx-lsp) and [surrealql-lsp](https://github.com/Ce11an/surrealql-lsp). (Both are well-worth checking out)
cc: @Ce11an, I got most of the way there by copying your implementation in surrealql-lsp. Hope that's ok 😄

feat: VSCode dev support

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/handle.rs
src/lsp.rs
src/test.rs

This PR adds support for the LLVM project's `compile_commands.json` and `compile_flags.txt` [standards](https://clang.llvm.org/docs/JSONCompilationDatabase.html). I created a [separate crate](https://github.com/WillLillis/compile_commands) to provide a wrapper type around the formats, which the server then depends on. 
The standard allows for a compile command to be associated with a given source file. From this command, we can extract additional include directories. In addition to searching default include directories (as before), the server will now check for additional include directories, respecting the source file a request was made in. This checks off another item from #80, and moves us one step closer to #85.
Closes #77

feat: Support compile_commands.json/compile_flags.txt, correct include directories

---

Cargo.lock
Cargo.toml

Continuation of #99, as publishing failed due to too many keywords in the Cargo.toml file.

chore: bump version to 0.7.3

---

Cargo.lock

chore: bump openssl version

---

Cargo.lock
Cargo.toml
src/lsp.rs
src/test.rs

Implements basic autocomplete for labels. There is a minor performance concern here, as we're running a tree-sitter query over the entire document for every autocomplete request that isn't initiated by a trigger character. If this proves to be too much of a slow down, I can look into speeding it up and/or putting this feature behind a configuration flag.
Quick demo using the example from #104:
This PR also bumps [tree-sitter-asm](https://github.com/RubixDev/tree-sitter-asm) to its current latest commit, rather than the older 0.1.0 release. There's been some nice improvements there lately and all of the project's tests still pass with the updates!
cc @ChillerDragon
Closes #104

feat: label autocomplete

---

Cargo.lock
src/handle.rs
src/lsp.rs
src/x86_parser.rs

Bumps all dependencies as possible, and addresses some of clippy's pedantic lints I missed previously.

chore: bump deps, address clippy lints

---

Cargo.lock
Cargo.toml

Bumps the version for a 0.7.4 release.
Includes some bug fixes, label autocomplete feature, and dependency bumps.

chore: bump version to 0.7.4

---

Cargo.lock
Cargo.toml

Turns out you can't publish to crates.io with a git dependency...
This reverts the change for `tree-sitter-asm` from its latest git commit to 0.1.0.

revert to tree-sitter 0.1.0 version

---

src/handle.rs

Returning an empty string in response to this requests causes neovim to display an error. See screenshot below (extracted from @ChillerDragon's report in #105):
Returning `None` instead fixes this.

fix: Return None on failure to find definition

---

src/handle.rs

Related to #111 
A few other places in the project return a response with `Some(json!(""))` rather than `None` for an empty result. This can cause Neovim at least (haven't tested with other editors) to display an error. Using `None` instead fixes this.

fix: Remove last uses of Some(json!(""))

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/handle.rs
src/lsp.rs
src/test.rs

The basic issue seemed to be that edits weren't properly applied to the tree, allowing for an OOB access in some situations following a deletion in the source file. As far as I can tell, bumping the tree-sitter version fixed the issue reported in #112, so I think this is a bug upstream on tree-sitter's end. If I'm wrong and the issue is still present, I'll get a minimal repo together and file an issue with them.
Closes #112

fix: Bump tree-sitter, tree-sitter-asm dependencies

---

src/handle.rs

It looks like I goofed on the path comparison code when comparing between the `uri` in the LSP client's request parameters and the `file` entry for each given compile command. The `file://` prefix in the parameter's `uri` field caused every comparison to evaluate to false. 
cc @RemezovaJulia
Closes #115

fix: remove file:// prefix in path comparison inside diagnostics handling code

---

src/handle.rs

The new uri API is a little awkward, missed this cleaner solution in #116

chore: cleanup previous fix

---

src/bin/main.rs
src/handle.rs
src/lsp.rs
src/parser.rs
src/test.rs

This adds hover support for labels as requested in #47. When a label is hovered over and it has data directly following it, said data will be shown in a hover window. Implementing this was fairly straightforward, but did require a bit of a refactor in the hover test code. Apologies for taking so long to implement this!
This PR also includes a little cleanup in the parsing code (not sure why clippy didn't catch these warnings in CI).
Quick demo using `samples/gas.s`:
Closes #47

feat: label hover data

---

.github/workflows/release.yml

This is a first pass on addressing #18 
I followed the [cross-compilation example](https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases#example-workflow-cross-compilation) from the suggested workflow. While everything *looks* reasonable, I'm not sure how to test it without pushing a new release tag.
cc @bergercookie I think it would be nice to be able to use this with coming `0.8.0` release. If you could give this a second look within the next week or two that would be greatly appreciated. Do you know any way we could test this? No pressure if you don't have the bandwidth, though, I can always try it and troubleshoot from there. 😄 
Closes #18

feat: add workflow to publish gh binaries

---

src/lsp.rs

The basic issue seemed to be that edits weren't properly applied to the tree, allowing for an OOB access in some situations following a deletion in the source file.  I think this is a bug upstream on tree-sitter's end, but I need to investigate further to try and get a minimal repro together to report. For now, we just manually check if a the position for a node's text is beyond the end of our current copy of the document. In such cases, we simply skip a check for that node.
Related #114 #112

fix: Avoid getting node texts beyond document boundaries

---

src/lsp.rs

Meant to do this awhile ago. Since the `Hash` trait was derived on the `Location` struct and we were able to update to the newest version of `lsp-types`, we can just use a `HashSet` when collecting reference, rather than a more expensive manual check against all current members in the  `Vec`.

chore: Cleanup up de-duping logic for get_ref_resp

---

src/bin/main.rs
src/lsp.rs

Adds a check for the (deprecated) `root_path` field when trying to determine a project's root directory. Also adds a log statement showing the initialization params received from the client.
Added as part of the investigation for #127

fix: Add check to root_path field for project path

---

src/lsp.rs

Currently the server uses the [`dirs` crate](https://crates.io/crates/dirs) to find the global configuration path. On MacOS this is unintuitively `$HOME/Library/Application Support/`. This PR adds `$HOME/.config` as an additional directory to search if the first check comes up empty.
cc @JezerM I don't have a Mac to test this locally. If you have the time, could you check if this resolves the behavior outlined in #127?
EDIT: Not sure why CI is failing, everything is passing locally in Ubuntu. Give me a minute to work this out :)

fix: Add additional global config path on macos

---

README.md
asm-lsp_config_schema.json
src/bin/main.rs
src/lsp.rs
src/test.rs
src/types.rs

This makes every item within `.asm-lsp.toml` optional. Leaving an item out of the config file is now the same as marking it as `false`. 
It was fine requiring every option in the config when there were only a few, but now that we've added a few more instruction sets and assemblers, I imagine this will become/already is quite annoying to users. In addition, we can now add additional instruction sets and assemblers without making a breaking change, as missing items will no longer lead to a de-serialization failure of the `TargetConfig` structure from `.asm-lsp.toml`.

feat: make config items optional

---

.github/workflows/release.yml

After some experimenting in a [throwaway repo](https://github.com/WillLillis/asm-lsp-test), I *think* that the non-Windows release actions should be patched. I'm still running into issues with the Windows runner (see #134), so that portion has been commented out for now. The plan is to run another release workflow manually to partially address #134 and #136. I'm planning on fixing the Windows-specific issues when I have some more free time.

fix(CI): Disable release Windows workflow, patch other release workflows

---

Cargo.lock
Cargo.toml
README.md
src/bin/main.rs
src/handle.rs
src/lsp.rs
src/test.rs
src/types.rs

This corrects the treatment of `compile_flags.txt` during the server's generation of diagnostics. The server now treats `compile_flags.txt` files correctly, as if they only contain flags. If such a file is loaded, the server will attempt to invoke `gcc` with the provided flags. If it fails to invoke `gcc`, it will also try `clang`. There is a new `opts` section of `.asm-lsp.toml` with an optional `compiler` entry. If the `compiler` field is set, the server will attempt to invoke the provided compiler in order to generate diagnostics. 
This also enables diagnostics by *default*. That is, if no compile command applies to the source file when a request comes in, the server will still try to invoke `gcc` (and if that fails, `clang`) on the contents of the current buffer, with the file path …

fix: proper usage of compile_flags.txt for diagnostics

---

src/handle.rs
src/lsp.rs

#148 pointed out a few issues with the server's current generation of diagnostics. 
First, error messages with both line and column information (I originally tested this feature with gcc, which only outputs line information) causes the regex to misbehave, reporting the column number as the line number. This was solved by introducing a second regex that looks for both numbers. If that fails to match properly, the original regex is used instead. 
Second, the source file *clearly* needs to be passed along as an argument to compiler when using `compile_flags.txt`. 
Lastly, I removed an early return which allows the server to still produce diagnostics when an empty `compile_flags.txt` file is used.
Partially addresses #148

fix: Issues with `compile_flags.txt`

---

src/bin/main.rs
src/handle.rs
src/lsp.rs
src/test.rs
src/types.rs

Whenever the server doesn't have an answer for a request (for example, you hover over something that it doesn't have information for), it sends an empty response. This looks like the following:
```rust
Response {
id, // id passed in for the corresponding request
result: None,
error: None,
};
```
When this response is sent to the [Helix](https://github.com/helix-editor/helix) LSP client, it shuts down the server with the following log:
```
[ERROR] Exiting asm-lsp after unexpected error: Parse(Error("data did not match any variant of untagged enum ServerMessage", line: 0, column: 0))
```
The easy solution for this is to detect if the lsp-client is helix at server start, and store that information in our `Config` object. If the client is helix and an empty response is going to be sent, we …

fix: Don't send empty response to Helix client

---

README.md

Update example config to use the zig compiler for `compile_flags.txt` generated diagnostics

---

.github/workflows/lint_and_test.yml
src/lsp.rs

Ran into some issues with CI while testing #158. Going to merge this in now to prevent future headaches, shouldn't cause any conflicts with open PRs.
EDIT: cc @Ultra-Code I have to disable some lints in order for CI to pass here. I think it's a false positive since taking the lint's suggestion results in a compile error (`PathBuf`'s `core::convert::Infallible` error type isn't treated as infallible for me locally at least), so I may be introducing a few conflicts. CI has to pass in order for your PR to get in, but regardless my apologies.

fix(CI): precommit hooks ruby dependency

---

Cargo.lock
Cargo.toml
README.md
asm-lsp/Cargo.toml
asm-lsp/bin/main.rs
asm-lsp/config_builder.rs
asm-lsp/lib.rs
asm-lsp/lsp.rs
asm_docs_parsing/Cargo.toml

I am greatly excited by the config improvements coming from #158. These changes do make the config a bit more complex though, which may be confusing/hard to track in large projects/ for new users. This PR adds a small CLI program that prompts a user through creating a `.asm-lsp.toml` config file, which should help manage that complexity. ~~I'll add some more details to this PR description (and some example gifs) once it's closer to being merged, but I wanted to open this up early for the sake of visibility.~~
~~Currently, the config builder program lives as a separate binary crate within the project. I think I'd like to change this to run as a subcommand of the main program (assuming it doesn't bloat the binary size by too much). Some documentation for this also needs to be added to the …

feat: Config builder

---

asm-lsp/test.rs

This ended up being a lot simpler than I initially thought. In our tests' setup code, we have the following race condition:
```rust
fn init_test_store(info: &GlobalInfo) -> ServerStore {
let mut store = ServerStore::default();
let mut x86_cache_path = get_cache_dir().unwrap();
x86_cache_path.push("x86_instr_docs.html");
if x86_cache_path.is_file() {
std::fs::remove_file(&x86_cache_path).unwrap(); // BAD CODE HERE!
}
...
}
```
With tests running on multiple threads, it's possible for one to check that the cache file exists, be interrupted, and after it's resumed a test runner on another thread has already removed it. This cache was in the test code because we used to pull this file down from the internet at the server's start. Some caching for it was added in #21, so it made sense to clear …

fix(CI): remove race-y code from tests

---

asm-lsp/lsp.rs

Follow up from #160 and #156.
Now that we have the latest stable running in CI, we can clean up some of the noise around irrefutable let patterns, which we previously had to manually ignore with a clippy annotation.

chore: cleanup around irrefutable let patterns

---

asm-lsp/config_builder.rs

The basic problem here is that windows allows you to omit a file name when referring to a file. That is, `gcc` is perfectly fine to refer to `gcc.exe`. However, calling `.is_file()` on a path ending with `gcc` where the file is actually `gcc.exe` will return `false`. This causes a bug in our compiler validation logic on Windows, leading us to tell users that their compiler couldn't be found when it definitely was. 
The fix is to simply iterate over common executable extension when the `is_file()` check fails. If any of these extension paths exist and point to a file, we'll consider that good enough:tm: and treat it as a valid compiler path. We'll still print a warning to the screen in this case, to avoid potential confusion.
Addresses the main issue raised in #173

fix(config builder): compiler validation on windows

---

asm-lsp/types.rs

Noticed that this could be removed while working on the surrounding code.

chore(lsp): remove stale `#[allow()]` annotation

---

README.md

Without the necessary background, it can be unclear what the various config fields do. Adding these comments in the README's example should help clear things up.
Closes  #174

fix(docs): clarify usage of config fields in example

---

asm-lsp/handle.rs
asm-lsp/lsp.rs
asm-lsp/types.rs

After dealing with a number of issues surrounding how paths are communicated from various lsp clients on Windows, I believe this should fix #173. The basic idea is this:
1. We see a leading slash '/' on a path on Windows
2. We see that the path contains a drive separator, ':' (this check is performed *after* percent decoding)
3. Remove the leading slash
Feels a little hacky, but in theory we should have a valid path after that.
@elli0t43 I don't currently have a full setup on Windows to test this with. I can get to that eventually, but if you have the time to test this fix that could really expedite things and would be greatly appreciated. :)

fix: Remove leading slash from paths on windows with colon drive separators

---

asm-lsp/bin/main.rs
asm-lsp/handle.rs
asm-lsp/lsp.rs

Two quick changes here.
1. Add a log about what compile command the server is attempting to invoke.
2. The extra formatting used in `:#?`-style debug logs aren't better compared to `:?` when used inside of neovim lsp log file, so I've swapped them out.

chore: add compile command log, remove pretty formatting from other logs

---

asm-lsp/lib.rs
asm-lsp/ustr.rs

fix: Remove `pub` marker from `ustr` and `lsp` mods

---

.pre-commit-config.yaml
asm-lsp/test.rs

By default, running `cargo clippy` doesn't cover test code. This PR correct a minor linting issue in the testing code and ensures that  CI runs this check in the future.

fix(CI): run clippy on test code

---

.gitattributes

In theory, with this change Github will ignore the html files we have in `docs_store` when calculating language stats for the repo.

chore(gh): Add a `.gitattributes` file 

---

asm-lsp/parser.rs
asm-lsp/test.rs

Some followup from #195. This PR does two things:
1. Reduce a fair amount of redundant code in the serialization tests through some simple macros. (Yay!)
2. Add a missing serialization test for the riscv instructions (Oops!)

chore: Test cleanup

---

docs_store/opcodes/avr.xml

* XML file has similar form to the x80 opcodes file with the following difference:
- Versions sections for different versions. If version has differences with other versions, it is named as <Version value=verison_name>. Other versions pointed as <Version value=All>.
- Each InstructionForm section has "summary" instead of global summary for Instruction.
- SREG - status registers section.
- Encoding is split into nibbles due to the official doc format. There could be 32 and 16 bit commands.
- Clocks has problem with format because each section contains clocks of all versions. It should be discussed.

add avr opcodes

---

Cargo.lock
Cargo.toml
asm-lsp/Cargo.toml
asm-lsp/config_builder.rs
asm-lsp/lsp.rs
asm-lsp/parser.rs
asm-lsp/test.rs
asm-lsp/types.rs
asm_docs_parsing/src/main.rs

- Fixes a bug I found in the config builder while debugging another issue
- Addresses some new clippy lints
- Bumps some dependencies
- Notably absent are the upgrades to bincode and tree-sitter. These will require a few non-trivial changes.

fix(config-builder): clear path lists in edge case, do some maintenance

---

asm-lsp/lsp.rs

I added support for the error format of the ca65 assembler.
i also have seen the comment on line 678, so i tried to avoid making more Regex shenanigan :see_no_evil:

add support for ca65 error messages

---

README.md
asm-lsp/bin/main.rs
asm-lsp/config_builder.rs
asm-lsp/handle.rs
asm-lsp/lsp.rs
asm-lsp/test.rs
asm-lsp/types.rs

Sending a response with both `error` and `result` set to `None` does not
conform to the LSP spec, and results in an error being displayed by
Neovim's client.
With this change, we no longer have to special-case Helix's client.
Also, this PR also makes use of the new nested if let chains.
- Closes #256

fix(lsp): send error response to request when no data is available
